version: '3'

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - sonarqube_net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:6.7
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=${DATABASE_USER}
      - SONARQUBE_JDBC_PASSWORD=${DATABASE_PASSWORD}
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/${DATABASE_NAME}
    depends_on:
      - postgres
    networks:
      - sonarqube_net

networks:
  sonarqube_net:
    driver: bridge

volumes:
  postgres-data:
